sys:
  logging_level: "INFO"
  logging_file: "history.log"
forwarders:
  slack:
    channel_setting: "default"
router:
  # Only send message when system is locked
  locked_only: true
  block_list:
    - "com.apple.MobileSMS"